GET  http://localhost:3333/user/allusers

###

POST http://localhost:3333/users/new
content-type: application/json

{
    "name": "joao",
    "email": "joao@email.com",
    "password": "Joao@123",
    "role": "ADMIN"
}

###
GET http://localhost:3333/users/user
Content-Type: application/json

{
    "email": "joao@email.com"
}

###
PATCH http://localhost:3333/users/edit
Content-Type: application/json

{
    "email": "joao@email.com",
    "name": "Rafael",
    "password": "03051979"
}

###

DELETE  http://localhost:3333/users/delete
Content-Type: application/json
x-api-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvYW9AZW1haWwuY29tIiwiaWF0IjoxNjc1OTg4ODY0LCJleHAiOjE2NzU5OTI0NjR9.CdYQ0GK0LEdZKffPLkPbwsJEIym-dIm17imW3Y4rzBI

{
    "email": "joao@email.com"
}

###

POST http://localhost:3333/auth/login
Content-Type: application/json

{
   "email": "joao@email.com",
    "password": "Joao@123"
}

### Product
POST http://localhost:3333/product/new
Content-Type: application/json
x-api-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvYW9AZW1haWwuY29tIiwiaWF0IjoxNjc1OTg4ODY0LCJleHAiOjE2NzU5OTI0NjR9.CdYQ0GK0LEdZKffPLkPbwsJEIym-dIm17imW3Y4rzBI

{
    "name": "Test Product",
    "image": "url/image",
    "price": 50,
    "quantity": 10
}

###
PATCH  http://localhost:3333/product/edit
Content-Type: application/json

{
    "productId": "b7ab3f92-3335-4c64-b885-d9d2e82234d9",
    "name": "new Test Product",
    "image": "new url/image",
    "price": "80",
    "quantity": 2
}
###
GET   http://localhost:3333/product/product
Content-Type: application/json

{
    "productId": "c256b486-64da-45d0-896b-ab3a2997db7e"
}
###
DELETE    http://localhost:3333/product/delete/c256b486-64da-45d0-896b-ab3a2997db7e
Content-Type: application/json