GET  http://localhost:3333/user/allusers

###

POST http://localhost:3333/users/new
content-type: application/json

{
    "name": "João",
    "email": "joao@email.com",
    "password": "123456"
}

###
GET http://localhost:3333/users/user
Content-Type: application/json

{
    "email": "joao@email.com"
}

###
PATCH http://localhost:3333/users/edit
Content-Type: application/json

{
    "email": "joao@email.com",
    "name": "Rafael",
    "password": "03051979"
}