GET  http://localhost:3333/user/allusers

###

POST http://localhost:3333/users/new
content-type: application/json

{
    "name": "rafael",
    "email": "rafael@email.com",
    "password": "Rafael@123",
    "role": "ADMIN"
}

###
GET http://localhost:3333/users/user
Content-Type: application/json

{
    "email": "joao@email.com"
}

###
PATCH http://localhost:3333/users/edit
Content-Type: application/json

{
    "email": "joao@email.com",
    "name": "Rafael",
    "password": "03051979"
}

###

DELETE  http://localhost:3333/users/delete
Content-Type: application/json
x-api-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhZmFlbEBlbWFpbC5jb20iLCJpYXQiOjE2NzU0NzYwMTEsImV4cCI6MTY3NTQ3OTYxMX0.PWICsMuEq4UcHiUY6lyMD4WLD7wWG-qbz0pww2i6xTA

{
    "email": "joao@email.com"
}

###

POST http://localhost:3333/auth/login
Content-Type: application/json

{
    "email": "rafael@email.com",
    "password": "Rafael@123"
}